### ISSUE TITLE
USER STORY: Guest check-in

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4#4]
As an **employee**, I can **check-in new guest dogs** so that **they appear in the guest list**

## Acceptance Criteria

- Easy to find check-in feature.

- Find and select of guest to check in.

- Reload of guest list with new guest in it.

## Tasks

- [ ] Add check-in button to guest list.

- [ ] Search database by name for guest to check-in.

- [ ] Add list of search result to select the guest to check in.
