### ISSUE TITLE
USER STORY: Basic project setup

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4#5]
As a **developer** I can **continue to develop the functionality of this project** so that **the project can be completed**

## Acceptance Criteria

- All pages/apps are created

- All setting for urls and so on are done

- All pages are reachable by using urls.

## Tasks

- [ ] Create apps for guests, reports, shopping- and todo-lists, subscription management

- [ ] Create and validate routing using the urls.py settings

- [ ] Create basic Views, Models, Controls for each app
