### ISSUE TITLE
USER STORY: User authentication

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4#6]
As a **user** I can **login** so that **I can use the app as my role allowes**

## Acceptance Criteria

- User can login with username and password

- No logged out user can use the app

- Two roles are defined as "user" and "admin"

## Tasks

- [ ] Create login system and page

- [ ] Create user table in database

- [ ] Create roles table in database with permission information
